use crate::output;
use crate::ssh_utils::{execute_remote_command, lookup_provider_server};
use airstack_config::AirstackConfig;
use anyhow::{Context, Result};
use clap::Subcommand;
use serde::Serialize;
use std::collections::{BTreeSet, HashMap};
use std::net::ToSocketAddrs;
use tokio::process::Command;

#[derive(Debug, Clone, Subcommand)]
pub enum EdgeCommands {
    #[command(about = "Preview reverse-proxy config and actions")]
    Plan,
    #[command(about = "Apply reverse-proxy config")]
    Apply,
    #[command(about = "Validate DNS and edge prerequisites")]
    Validate,
    #[command(about = "Show edge status including managed paths and config drift")]
    Status,
    #[command(about = "Diagnose TLS/ACME edge issues with remediation hints")]
    Diagnose,
}

#[derive(Debug, Serialize)]
struct EdgeStatus {
    provider: String,
    managed_file_paths: Vec<String>,
    generated_file_warning: String,
    include_file: Option<String>,
    sites: Vec<EdgeSiteStatus>,
    rendered_vs_live_diff: Vec<String>,
}

#[derive(Debug, Serialize)]
struct EdgeSiteStatus {
    host: String,
    dns_resolved: bool,
    upstream_service: String,
    upstream_port: u16,
    static_routes: Vec<EdgeStaticStatus>,
}

#[derive(Debug, Serialize)]
struct EdgeStaticStatus {
    path_prefix: String,
    root: String,
    host_path: Option<String>,
}

pub async fn run(config_path: &str, command: EdgeCommands) -> Result<()> {
    let config = AirstackConfig::load(config_path).context("Failed to load configuration")?;
    let edge = config.edge.as_ref().context("No [edge] config defined")?;

    match command {
        EdgeCommands::Plan => plan(edge),
        EdgeCommands::Validate => validate(edge),
        EdgeCommands::Status => status(&config).await,
        EdgeCommands::Diagnose => diagnose(&config).await,
        EdgeCommands::Apply => apply_from_config(&config).await,
    }
}

fn plan(edge: &airstack_config::EdgeConfig) -> Result<()> {
    let rendered = render_caddyfile(edge);
    output::line("🧩 Edge Plan");
    output::line(format!("Provider: {}", edge.provider));
    output::line("Generated Caddyfile:");
    output::line(rendered);
    Ok(())
}

fn validate(edge: &airstack_config::EdgeConfig) -> Result<()> {
    let mut failures = Vec::new();
    for site in &edge.sites {
        let ok = (site.host.as_str(), 443)
            .to_socket_addrs()
            .map(|mut a| a.next().is_some())
            .unwrap_or(false);
        if !ok {
            failures.push(format!("{} does not resolve for :443", site.host));
        }
    }

    if failures.is_empty() {
        output::line("✅ edge validate: DNS prerequisites look good");
        return Ok(());
    }

    output::line("❌ edge validate failed:");
    for f in &failures {
        output::line(format!("- {}", f));
    }
    anyhow::bail!("edge validation failed")
}

async fn status(config: &AirstackConfig) -> Result<()> {
    let edge = config.edge.as_ref().context("No [edge] config defined")?;
    let sites = edge
        .sites
        .iter()
        .map(|s| EdgeSiteStatus {
            host: s.host.clone(),
            dns_resolved: (s.host.as_str(), 443)
                .to_socket_addrs()
                .map(|mut a| a.next().is_some())
                .unwrap_or(false),
            upstream_service: s.upstream_service.clone(),
            upstream_port: s.upstream_port,
            static_routes: s
                .static_routes
                .iter()
                .map(|st| EdgeStaticStatus {
                    path_prefix: st.path_prefix.clone(),
                    root: st.root.clone(),
                    host_path: st.host_path.clone(),
                })
                .collect(),
        })
        .collect::<Vec<_>>();

    let rendered = render_caddyfile(edge);
    let managed_file_paths = detect_managed_paths(config).await.unwrap_or_else(|| {
        vec![
            "/opt/aria/Caddyfile".to_string(),
            "/etc/caddy/Caddyfile".to_string(),
        ]
    });
    let live = read_live_caddyfile(config).await.unwrap_or_default();
    let rendered_vs_live_diff = unified_diff_preview(&live, &rendered, 200);

    let payload = EdgeStatus {
        provider: edge.provider.clone(),
        managed_file_paths,
        generated_file_warning:
            "These files are generated by `airstack edge apply` and manual edits may be overwritten."
                .to_string(),
        include_file: edge.extra_include_file.clone(),
        sites,
        rendered_vs_live_diff,
    };

    if output::is_json() {
        output::emit_json(&payload)?;
    } else {
        output::line("🌐 Edge Status");
        output::line(format!("Provider: {}", payload.provider));
        output::line("Managed files:");
        for p in &payload.managed_file_paths {
            output::line(format!("- {}", p));
        }
        output::line(format!("Warning: {}", payload.generated_file_warning));
        if let Some(include_file) = &payload.include_file {
            output::line(format!("Stable include file: {}", include_file));
        }

        for s in &payload.sites {
            output::line(format!(
                "- {} -> {}:{} (dns={})",
                s.host, s.upstream_service, s.upstream_port, s.dns_resolved
            ));
            for st in &s.static_routes {
                output::line(format!(
                    "    static {} => {}{}",
                    st.path_prefix,
                    st.root,
                    st.host_path
                        .as_ref()
                        .map(|hp| format!(" (host_path={hp})"))
                        .unwrap_or_default()
                ));
            }
        }

        if payload.rendered_vs_live_diff.is_empty() {
            output::line("Rendered config matches live config.");
        } else {
            output::line("Rendered vs live diff preview:");
            for line in &payload.rendered_vs_live_diff {
                output::line(format!("  {}", line));
            }
        }
    }

    Ok(())
}

#[derive(Debug, Serialize)]
struct EdgeDiagnosis {
    host: String,
    dns_resolved: bool,
    dns_ttl_secs: Option<u32>,
    nameservers: Vec<String>,
    tls_handshake_ok: bool,
    remediation: Vec<String>,
}

#[derive(Debug, Serialize)]
struct EdgeApplySummary {
    changed: bool,
    restart_required: bool,
    target: String,
    diff_preview: Vec<String>,
}

async fn diagnose(config: &AirstackConfig) -> Result<()> {
    let edge = config.edge.as_ref().context("No [edge] config defined")?;
    let expected_edge_ip = resolve_edge_server_ip(config).await;

    let mut rows = Vec::new();
    for site in &edge.sites {
        let resolved = (site.host.as_str(), 443)
            .to_socket_addrs()
            .map(|iter| iter.map(|a| a.ip().to_string()).collect::<Vec<_>>())
            .unwrap_or_default();
        let dns_ok = !resolved.is_empty();
        let dns_ttl_secs = query_dns_ttl(&site.host).await;
        let nameservers = query_nameservers(&site.host).await;
        let dns_target_matches = expected_edge_ip
            .as_ref()
            .map(|ip| resolved.iter().any(|r| r == ip))
            .unwrap_or(true);

        let mut tls_ok = false;
        let mut remediation = Vec::new();
        if !dns_ok {
            remediation.push(format!(
                "DNS: ensure A/AAAA for '{}' points to edge host before ACME issuance",
                site.host
            ));
            if nameservers.is_empty() {
                remediation.push("NS visibility: no nameservers discovered for host domain; verify delegation at registrar".to_string());
            }
        } else if !dns_target_matches {
            remediation.push(format!(
                "DNS mismatch: '{}' resolves to [{}], expected edge IP {}",
                site.host,
                resolved.join(", "),
                expected_edge_ip
                    .clone()
                    .unwrap_or_else(|| "unknown".to_string())
            ));
            remediation
                .push("Update DNS A/AAAA to the expected edge IP before ACME issuance".to_string());
        } else {
            let out = Command::new("sh")
                .arg("-lc")
                .arg(format!(
                    "echo | openssl s_client -connect {h}:443 -servername {h} -brief 2>/dev/null",
                    h = site.host
                ))
                .output()
                .await
                .context("Failed to run openssl for edge diagnosis")?;
            tls_ok = out.status.success();
            if !tls_ok {
                remediation.push(format!(
                    "TLS: verify port 443 open and Caddy running, then run `airstack edge apply`"
                ));
                remediation.push(format!(
                    "ACME: check Caddy logs (`journalctl -u caddy -n 200`) for challenge failure details"
                ));
            }
        }

        if site.tls_email.is_none() {
            remediation.push(format!(
                "Config: set tls_email for '{}' to improve ACME ops visibility",
                site.host
            ));
        }

        rows.push(EdgeDiagnosis {
            host: site.host.clone(),
            dns_resolved: dns_ok,
            dns_ttl_secs,
            nameservers,
            tls_handshake_ok: tls_ok,
            remediation,
        });
    }

    if output::is_json() {
        output::emit_json(&serde_json::json!({ "diagnosis": rows }))?;
    } else {
        output::line("🩺 Edge Diagnose");
        for row in &rows {
            let ok = row.dns_resolved && row.tls_handshake_ok;
            let mark = if ok { "✅" } else { "❌" };
            output::line(format!(
                "{} {} dns={} ttl={}ns={} tls={}",
                mark,
                row.host,
                row.dns_resolved,
                row.dns_ttl_secs
                    .map(|v| v.to_string())
                    .unwrap_or_else(|| "?".to_string()),
                if row.nameservers.is_empty() {
                    "?".to_string()
                } else {
                    row.nameservers.join(",")
                },
                row.tls_handshake_ok
            ));
            for hint in &row.remediation {
                output::line(format!("   - {}", hint));
            }
        }
    }

    if rows.iter().any(|r| !r.dns_resolved || !r.tls_handshake_ok) {
        anyhow::bail!("edge diagnose found actionable issues")
    }
    Ok(())
}

pub async fn apply_from_config(config: &AirstackConfig) -> Result<()> {
    let edge = config.edge.as_ref().context("No [edge] config defined")?;
    if edge.provider != "caddy" {
        anyhow::bail!("Only edge.provider='caddy' is currently supported");
    }

    let infra = config
        .infra
        .as_ref()
        .context("Edge apply requires infra.servers")?;
    let server = infra
        .servers
        .first()
        .context("Edge apply requires at least one server")?;

    let caddyfile = render_caddyfile(edge);
    let include_file = edge.extra_include_file.clone().unwrap_or_default();

    let upload_script = format!(
        r#"set -e
 tmp="$(mktemp /tmp/airstack-caddy.XXXXXX)"
 cat > "$tmp" <<'CADDY'
 {caddy}
 CADDY
 
 container_id=""
 if command -v docker >/dev/null 2>&1; then
   container_id="$(docker ps -aqf 'name=^/caddy$' | head -n1 || true)"
 fi
 
 target=""
 if [ -n "$container_id" ]; then
   mount_source="$(docker inspect -f '{{{{range .Mounts}}}}{{{{if eq .Destination "/etc/caddy/Caddyfile"}}}}{{{{.Source}}}}{{{{end}}}}{{{{end}}}}' caddy 2>/dev/null || true)"
   if [ -n "$mount_source" ]; then
     target="$mount_source"
   fi
 fi
 
 if [ -z "$target" ]; then
   for p in /opt/aria/Caddyfile /etc/caddy/Caddyfile; do
     if [ -e "$p" ]; then
       target="$p"
       break
     fi
   done
 fi
 
 if [ -n "{include_file}" ]; then
   mkdir -p "$(dirname "{include_file}")" 2>/dev/null || true
   touch "{include_file}" 2>/dev/null || true
 fi
 
 changed=1
 if [ -n "$target" ] && [ -f "$target" ]; then
   if cmp -s "$tmp" "$target"; then
     changed=0
   fi
 fi
 
 if [ "$changed" -eq 0 ]; then
   echo "changed=0 restart=0 target=${{target:-none}}"
   rm -f "$tmp"
   exit 0
 fi
 
 host_write_ok=0
 if [ -n "$target" ]; then
   mkdir -p "$(dirname "$target")" 2>/dev/null || true
   if cp "$tmp" "$target" 2>/dev/null; then
     host_write_ok=1
   fi
 fi
 
 if [ "$host_write_ok" -eq 0 ] && [ -n "$container_id" ]; then
   if [ -e /etc/caddy/Caddyfile ]; then
     diff -u /etc/caddy/Caddyfile "$tmp" 2>/dev/null | head -n 200 || true
   fi
   docker cp "$tmp" caddy:/etc/caddy/Caddyfile
   docker exec caddy sh -lc 'caddy validate --config /etc/caddy/Caddyfile' || true
   docker restart caddy >/dev/null 2>&1 || true
   echo "changed=1 restart=1 target=container:/etc/caddy/Caddyfile"
   rm -f "$tmp"
   exit 0
 fi
 
 if [ "$host_write_ok" -eq 1 ]; then
   if [ -f "$target" ]; then
     diff -u "$target" "$tmp" 2>/dev/null | head -n 200 || true
   fi
   restart_required=0
   if [ -n "$container_id" ]; then
     docker restart caddy >/dev/null 2>&1 || true
     restart_required=1
   elif command -v caddy >/dev/null 2>&1; then
     caddy validate --config "$target"
     if command -v systemctl >/dev/null 2>&1; then
       systemctl reload caddy || true
       restart_required=1
     fi
   fi
   echo "changed=1 restart=${{restart_required}} target=$target"
   rm -f "$tmp"
   exit 0
 fi
 
 echo "failed to write Caddyfile (host path not writable and no caddy container fallback)" >&2
 rm -f "$tmp"
 exit 1
 "#,
        caddy = caddyfile,
        include_file = include_file
    );

    let out = execute_remote_command(
        server,
        &["sh".to_string(), "-lc".to_string(), upload_script],
    )
    .await?;

    if !out.status.success() {
        let stderr = String::from_utf8_lossy(&out.stderr);
        anyhow::bail!("Edge apply failed: {}", stderr.trim());
    }

    let stdout = String::from_utf8_lossy(&out.stdout);
    let summary = parse_apply_summary(&stdout);
    if output::is_json() {
        output::emit_json(&summary)?;
        return Ok(());
    }

    output::line(format!(
        "✅ edge apply: changed={} restart={} target={}",
        summary.changed, summary.restart_required, summary.target
    ));
    if !summary.diff_preview.is_empty() {
        output::line("ℹ️ edge apply: diff preview");
        for line in &summary.diff_preview {
            output::line(format!("   {}", line));
        }
    }
    if !summary.changed {
        output::line("ℹ️ edge apply: no changes needed");
    } else {
        output::line("ℹ️ edge apply: config updated");
    }
    Ok(())
}

async fn resolve_edge_server_ip(config: &AirstackConfig) -> Option<String> {
    let infra = config.infra.as_ref()?;
    let server = infra.servers.first()?;
    let provider_server = lookup_provider_server(server).await.ok()?;
    provider_server.public_ip
}

fn render_caddyfile(edge: &airstack_config::EdgeConfig) -> String {
    let mut lines = Vec::new();
    lines.push("# Managed by airstack edge apply. Manual edits may be overwritten.".to_string());
    if let Some(include_file) = &edge.extra_include_file {
        lines.push(format!("import {}", include_file));
        lines.push(String::new());
    }

    for site in &edge.sites {
        lines.push(format!("{} {{", site.host));
        if site.redirect_http.unwrap_or(true) {
            lines.push("  @http protocol http".to_string());
            lines.push("  redir @http https://{host}{uri} 308".to_string());
        }
        if let Some(email) = &site.tls_email {
            lines.push(format!("  tls {}", email));
        }

        let mut idx = 0usize;
        for route in &site.static_routes {
            let matcher = format!("@static_{} path {}*", idx, route.path_prefix);
            lines.push(format!("  {}", matcher));
            lines.push(format!("  handle @static_{} {{", idx));
            lines.push(format!("    root * {}", route.root));
            emit_headers(&mut lines, route.headers.as_ref(), 4);
            if route.browse.unwrap_or(false) {
                lines.push("    file_server browse".to_string());
            } else {
                lines.push("    file_server".to_string());
            }
            lines.push("  }".to_string());
            idx += 1;
        }

        for route in &site.routes {
            let matcher = format!("@route_{} path {}*", idx, route.path_prefix);
            lines.push(format!("  {}", matcher));
            lines.push(format!("  handle @route_{} {{", idx));
            if route.strip_prefix.unwrap_or(false) {
                lines.push(format!("    uri strip_prefix {}", route.path_prefix));
            }
            emit_headers(&mut lines, route.headers.as_ref(), 4);
            if let Some(upstream) = &route.upstream {
                lines.push(format!("    reverse_proxy {}", upstream));
            }
            lines.push("  }".to_string());
            idx += 1;
        }

        if let Some(nearest) = &site.nearest {
            let header = nearest.header.as_deref().unwrap_or("CF-IPCountry");
            for region in &nearest.regions {
                let matcher = format!(
                    "@region_{} header_regexp {} ^({})$",
                    idx,
                    header,
                    region
                        .countries
                        .iter()
                        .map(|c| c.trim().to_ascii_uppercase())
                        .collect::<Vec<_>>()
                        .join("|")
                );
                lines.push(format!("  {}", matcher));
                lines.push(format!("  handle @region_{} {{", idx));
                lines.push(format!("    reverse_proxy {}", region.upstream));
                lines.push("  }".to_string());
                idx += 1;
            }
            let default_upstream = nearest
                .default_upstream
                .clone()
                .unwrap_or_else(|| format!("{}:{}", site.upstream_service, site.upstream_port));
            lines.push(format!("  reverse_proxy {}", default_upstream));
        } else {
            lines.push(format!(
                "  reverse_proxy {}:{}",
                site.upstream_service, site.upstream_port
            ));
        }
        lines.push("}".to_string());
        lines.push(String::new());
    }
    lines.join("\n")
}

fn emit_headers(lines: &mut Vec<String>, headers: Option<&HashMap<String, String>>, indent: usize) {
    let Some(headers) = headers else {
        return;
    };
    let mut sorted = headers.iter().collect::<Vec<_>>();
    sorted.sort_by(|a, b| a.0.cmp(b.0));
    for (k, v) in sorted {
        lines.push(format!(
            "{}header {} \"{}\"",
            " ".repeat(indent),
            k,
            escape_caddy_string(v)
        ));
    }
}

fn escape_caddy_string(value: &str) -> String {
    value.replace('"', "\\\"")
}

async fn query_dns_ttl(host: &str) -> Option<u32> {
    let out = Command::new("sh")
        .arg("-lc")
        .arg(format!(
            "dig +noall +answer A {} 2>/dev/null | head -n 1",
            host
        ))
        .output()
        .await
        .ok()?;
    if !out.status.success() {
        return None;
    }
    let line = String::from_utf8_lossy(&out.stdout).trim().to_string();
    if line.is_empty() {
        return None;
    }
    let parts = line.split_whitespace().collect::<Vec<_>>();
    if parts.len() < 2 {
        return None;
    }
    parts.get(1)?.parse::<u32>().ok()
}

async fn query_nameservers(host: &str) -> Vec<String> {
    let apex = derive_apex(host);
    let cmd = format!(
        "dig +short NS {host} 2>/dev/null; dig +short NS {apex} 2>/dev/null",
        host = host,
        apex = apex
    );
    let out = Command::new("sh").arg("-lc").arg(cmd).output().await;
    let Ok(out) = out else {
        return Vec::new();
    };
    if !out.status.success() {
        return Vec::new();
    }
    let mut uniq = BTreeSet::new();
    for line in String::from_utf8_lossy(&out.stdout).lines() {
        let ns = line.trim().trim_end_matches('.');
        if !ns.is_empty() {
            uniq.insert(ns.to_string());
        }
    }
    uniq.into_iter().collect()
}

fn derive_apex(host: &str) -> String {
    let parts = host.split('.').collect::<Vec<_>>();
    if parts.len() >= 2 {
        format!("{}.{}", parts[parts.len() - 2], parts[parts.len() - 1])
    } else {
        host.to_string()
    }
}

fn parse_apply_summary(stdout: &str) -> EdgeApplySummary {
    let mut changed = false;
    let mut restart_required = false;
    let mut target = "unknown".to_string();
    let mut diff_preview = Vec::new();

    for line in stdout.lines().map(str::trim).filter(|l| !l.is_empty()) {
        if let Some(rest) = line.strip_prefix("changed=") {
            let mut ch = None;
            let mut rs = None;
            let mut tg = None;
            for part in rest.split_whitespace() {
                if let Some(v) = part.strip_prefix("restart=") {
                    rs = Some(v == "1" || v.eq_ignore_ascii_case("true"));
                } else if let Some(v) = part.strip_prefix("target=") {
                    tg = Some(v.to_string());
                } else if ch.is_none() {
                    ch = Some(part == "1" || part.eq_ignore_ascii_case("true"));
                }
            }
            changed = ch.unwrap_or(false);
            restart_required = rs.unwrap_or(false);
            if let Some(t) = tg {
                target = t;
            }
            continue;
        }

        if line.starts_with("---")
            || line.starts_with("+++")
            || line.starts_with("@@")
            || line.starts_with('+')
            || line.starts_with('-')
        {
            if diff_preview.len() < 80 {
                diff_preview.push(line.to_string());
            }
        }
    }

    EdgeApplySummary {
        changed,
        restart_required,
        target,
        diff_preview,
    }
}

async fn detect_managed_paths(config: &AirstackConfig) -> Option<Vec<String>> {
    let infra = config.infra.as_ref()?;
    let server = infra.servers.first()?;

    let script = r#"set -e
paths=""
container_id=""
if command -v docker >/dev/null 2>&1; then
  container_id="$(docker ps -aqf 'name=^/caddy$' | head -n1 || true)"
fi
if [ -n "$container_id" ]; then
  mount_source="$(docker inspect -f '{{range .Mounts}}{{if eq .Destination "/etc/caddy/Caddyfile"}}{{.Source}}{{end}}{{end}}' caddy 2>/dev/null || true)"
  if [ -n "$mount_source" ]; then
    paths="$paths\n$mount_source"
  fi
  paths="$paths\ncontainer:/etc/caddy/Caddyfile"
fi
for p in /opt/aria/Caddyfile /etc/caddy/Caddyfile; do
  if [ -e "$p" ]; then
    paths="$paths\n$p"
  fi
done
printf '%s\n' "$paths" | sed '/^$/d' | sort -u
"#;

    let out = execute_remote_command(
        server,
        &["sh".to_string(), "-lc".to_string(), script.to_string()],
    )
    .await
    .ok()?;
    if !out.status.success() {
        return None;
    }

    let mut seen = BTreeSet::new();
    for line in String::from_utf8_lossy(&out.stdout).lines() {
        let line = line.trim();
        if !line.is_empty() {
            seen.insert(line.to_string());
        }
    }
    Some(seen.into_iter().collect())
}

async fn read_live_caddyfile(config: &AirstackConfig) -> Option<String> {
    let infra = config.infra.as_ref()?;
    let server = infra.servers.first()?;

    let script = r#"set -e
container_id=""
if command -v docker >/dev/null 2>&1; then
  container_id="$(docker ps -aqf 'name=^/caddy$' | head -n1 || true)"
fi
if [ -n "$container_id" ]; then
  mount_source="$(docker inspect -f '{{range .Mounts}}{{if eq .Destination "/etc/caddy/Caddyfile"}}{{.Source}}{{end}}{{end}}' caddy 2>/dev/null || true)"
  if [ -n "$mount_source" ] && [ -f "$mount_source" ]; then
    cat "$mount_source"
    exit 0
  fi
  docker exec caddy sh -lc 'cat /etc/caddy/Caddyfile' 2>/dev/null && exit 0
fi
for p in /opt/aria/Caddyfile /etc/caddy/Caddyfile; do
  if [ -f "$p" ]; then
    cat "$p"
    exit 0
  fi
done
exit 0
"#;

    let out = execute_remote_command(
        server,
        &["sh".to_string(), "-lc".to_string(), script.to_string()],
    )
    .await
    .ok()?;
    Some(String::from_utf8_lossy(&out.stdout).to_string())
}

fn unified_diff_preview(old_text: &str, new_text: &str, max_lines: usize) -> Vec<String> {
    if old_text == new_text {
        return Vec::new();
    }
    let mut out = Vec::new();
    let old: Vec<&str> = old_text.lines().collect();
    let new: Vec<&str> = new_text.lines().collect();
    let max = old.len().max(new.len());
    for i in 0..max {
        let a = old.get(i).copied().unwrap_or("");
        let b = new.get(i).copied().unwrap_or("");
        if a == b {
            continue;
        }
        if out.len() >= max_lines {
            break;
        }
        out.push(format!("@@ line {} @@", i + 1));
        if !a.is_empty() {
            out.push(format!("-{}", a));
        }
        if !b.is_empty() {
            out.push(format!("+{}", b));
        }
        if out.len() >= max_lines {
            break;
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use airstack_config::{
        EdgeConfig, EdgeNearestConfig, EdgeNearestRegionConfig, EdgeRouteConfig, EdgeSiteConfig,
        EdgeStaticRouteConfig,
    };

    #[test]
    fn render_caddyfile_includes_static_and_custom_routes() {
        let edge = EdgeConfig {
            provider: "caddy".to_string(),
            extra_include_file: Some("/opt/aria/Caddy.extra".to_string()),
            sites: vec![EdgeSiteConfig {
                host: "example.com".to_string(),
                upstream_service: "web".to_string(),
                upstream_port: 8080,
                tls_email: Some("ops@example.com".to_string()),
                redirect_http: Some(true),
                nearest: None,
                static_routes: vec![EdgeStaticRouteConfig {
                    path_prefix: "/downloads".to_string(),
                    root: "/srv/downloads".to_string(),
                    browse: Some(false),
                    headers: Some(HashMap::from([(
                        "Cache-Control".to_string(),
                        "public, max-age=300".to_string(),
                    )])),
                    host_path: Some("/srv/downloads".to_string()),
                }],
                routes: vec![EdgeRouteConfig {
                    path_prefix: "/internal".to_string(),
                    upstream: Some("web:9090".to_string()),
                    strip_prefix: Some(true),
                    headers: None,
                }],
            }],
        };

        let rendered = render_caddyfile(&edge);
        assert!(rendered.contains("import /opt/aria/Caddy.extra"));
        assert!(rendered.contains("handle @static_0"));
        assert!(rendered.contains("root * /srv/downloads"));
        assert!(rendered.contains("file_server"));
        assert!(rendered.contains("handle @route_1"));
        assert!(rendered.contains("uri strip_prefix /internal"));
        assert!(rendered.contains("reverse_proxy web:9090"));
        assert!(rendered.contains("reverse_proxy web:8080"));
    }

    #[test]
    fn render_caddyfile_includes_nearest_geo_header_routes() {
        let edge = EdgeConfig {
            provider: "caddy".to_string(),
            extra_include_file: None,
            sites: vec![EdgeSiteConfig {
                host: "backend.quilt.sh".to_string(),
                upstream_service: "api_us".to_string(),
                upstream_port: 8080,
                tls_email: Some("ops@quilt.sh".to_string()),
                redirect_http: Some(true),
                nearest: Some(EdgeNearestConfig {
                    method: Some("geo-header".to_string()),
                    header: Some("CF-IPCountry".to_string()),
                    default_upstream: Some("api_us:8080".to_string()),
                    regions: vec![EdgeNearestRegionConfig {
                        name: "eu".to_string(),
                        countries: vec!["GB".to_string(), "DE".to_string(), "FR".to_string()],
                        upstream: "api_eu:8080".to_string(),
                    }],
                }),
                static_routes: vec![],
                routes: vec![],
            }],
        };

        let rendered = render_caddyfile(&edge);
        assert!(rendered.contains("@region_0 header_regexp CF-IPCountry ^(GB|DE|FR)$"));
        assert!(rendered.contains("handle @region_0"));
        assert!(rendered.contains("reverse_proxy api_eu:8080"));
        assert!(rendered.contains("reverse_proxy api_us:8080"));
    }
}
