pub mod apply;
pub mod backup;
pub mod cexec;
pub mod cli;
pub mod deploy;
pub mod destroy;
pub mod doctor;
pub mod drift;
pub mod edge;
pub mod init;
pub mod logs;
pub mod plan;
pub mod reconcile;
pub mod registry;
pub mod release;
pub mod runbook;
pub mod scale;
pub mod secrets;
pub mod ship;
pub mod ssh;
pub mod status;
#[cfg(feature = "tui")]
pub mod tui;
#[cfg(not(feature = "tui"))]
#[path = "tui_stub.rs"]
pub mod tui;
pub mod up;
